version: "3"

networks:
  app:

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - app

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    depends_on:
      - loki
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
      - promtail
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    networks:
      - app